MapHeader_5C:	maphdr	"level/header/5C.bin", ForegroundLayout_5C, BlockLayout_5C.bin, BackgroundLayout_56_5C, EnemyLayout_5C
MapHeader_22:	maphdr	"level/header/22.bin", ForegroundLayout_22, BlockLayout_22.bin, BackgroundLayout_22, EnemyLayout_22
MapHeader_7C:	maphdr	"level/header/7C.bin", ForegroundLayout_7C, BlockLayout_7C.bin, BackgroundLayout_7C, EnemyLayout_7C
MapHeader_7D:	maphdr	"level/header/7D.bin", ForegroundLayout_7D, BlockLayout_7D.bin, BackgroundLayout_7D, EnemyLayout_7D
MapHeader_7A:	maphdr	"level/header/7A.bin", ForegroundLayout_7A, BlockLayout_7A.bin, BackgroundLayout_32_4D_4E_6E_7A, EnemyLayout_7A
MapHeader_7B:	maphdr	"level/header/7B.bin", ForegroundLayout_7B, BlockLayout_7B.bin, BackgroundLayout_4A_6C_6D_7B, EnemyLayout_7B
MapHeader_59:	maphdr	"level/header/59.bin", ForegroundLayout_59, BlockLayout_59.bin, BackgroundLayout_59, EnemyLayout_59
MapHeader_09_1A_41_42_48:	maphdr	"level/header/09.bin", ForegroundLayout_09, BlockLayout_09.bin, BackgroundLayout_09, EnemyLayout_09
MapHeader_47:	maphdr	"level/header/47.bin", ForegroundLayout_47, BlockLayout_47.bin, BackgroundLayout_47_77, EnemyLayout_47
MapHeader_27:	maphdr	"level/header/27.bin", ForegroundLayout_27, BlockLayout_27.bin, BackgroundLayout_27, EnemyLayout_27
MapHeader_12:	maphdr	"level/header/12.bin", ForegroundLayout_12, BlockLayout_12.bin, BackgroundLayout_12, EnemyLayout_12
MapHeader_11:	maphdr	"level/header/11.bin", ForegroundLayout_11, BlockLayout_11.bin, BackgroundLayout_11, EnemyLayout_11
MapHeader_5A:	maphdr	"level/header/5A.bin", ForegroundLayout_5A, BlockLayout_5A.bin, BackgroundLayout_57_5A, EnemyLayout_5A
MapHeader_10:	maphdr	"level/header/10.bin", ForegroundLayout_10, BlockLayout_10.bin, BackgroundLayout_10, EnemyLayout_10
MapHeader_26:	maphdr	"level/header/26.bin", ForegroundLayout_26, BlockLayout_26.bin, BackgroundLayout_26, EnemyLayout_26
MapHeader_58:	maphdr	"level/header/58.bin", ForegroundLayout_58, BlockLayout_58.bin, BackgroundLayout_58, EnemyLayout_58
	dc.b   0, $12, 0, $36, $3C, $26, 0, $28		; some junk data
MapHeader_3C:	maphdr	"level/header/3C.bin", ForegroundLayout_3C, BlockLayout_3C.bin, BackgroundLayout_3C, EnemyLayout_3C
MapHeader_3D:	maphdr	"level/header/3D.bin", ForegroundLayout_3D, BlockLayout_3D.bin, BackgroundLayout_3D, EnemyLayout_3D
MapHeader_3E:	maphdr	"level/header/3E.bin", ForegroundLayout_3E, BlockLayout_3E.bin, BackgroundLayout_3E, EnemyLayout_3E
MapHeader_00:	maphdr	"level/header/00.bin", ForegroundLayout_00, BlockLayout_00.bin, BackgroundLayout_00, EnemyLayout_00
MapHeader_01:	maphdr	"level/header/01.bin", ForegroundLayout_01, BlockLayout_01.bin, BackgroundLayout_01, EnemyLayout_01
MapHeader_02:	maphdr	"level/header/02.bin", ForegroundLayout_02, BlockLayout_02.bin, BackgroundLayout_02, EnemyLayout_02
MapHeader_03:	maphdr	"level/header/03.bin", ForegroundLayout_03, BlockLayout_03.bin, BackgroundLayout_03, EnemyLayout_03
MapHeader_04:	maphdr	"level/header/04.bin", ForegroundLayout_04, BlockLayout_04.bin, BackgroundLayout_04, EnemyLayout_04
MapHeader_05:	maphdr	"level/header/05.bin", ForegroundLayout_05, BlockLayout_05.bin, BackgroundLayout_05, EnemyLayout_05
MapHeader_08:	maphdr	"level/header/08.bin", ForegroundLayout_08, BlockLayout_08.bin, BackgroundLayout_08, EnemyLayout_08
MapHeader_15:	maphdr	"level/header/15.bin", ForegroundLayout_15, BlockLayout_15.bin, BackgroundLayout_15, EnemyLayout_15
MapHeader_16:	maphdr	"level/header/16.bin", ForegroundLayout_16, BlockLayout_16.bin, BackgroundLayout_16, EnemyLayout_16
MapHeader_40:	maphdr	"level/header/40.bin", ForegroundLayout_40, BlockLayout_40.bin, BackgroundLayout_40_76, EnemyLayout_40
MapHeader_2C:	maphdr	"level/header/2C.bin", ForegroundLayout_2C, BlockLayout_2C.bin, BackgroundLayout_2C, EnemyLayout_2C
MapHeader_2D:	maphdr	"level/header/2D.bin", ForegroundLayout_2D, BlockLayout_2D.bin, BackgroundLayout_2D_2F, EnemyLayout_2D
MapHeader_4A:	maphdr	"level/header/4A.bin", ForegroundLayout_4A, BlockLayout_4A.bin, BackgroundLayout_4A_6C_6D_7B, EnemyLayout_4A
MapHeader_4F:	maphdr	"level/header/4F.bin", ForegroundLayout_4F, BlockLayout_4F.bin, BackgroundLayout_4F, EnemyLayout_4F
MapHeader_18:	maphdr	"level/header/18.bin", ForegroundLayout_18, BlockLayout_18.bin, BackgroundLayout_18, EnemyLayout_18
MapHeader_19:	maphdr	"level/header/19.bin", ForegroundLayout_19, BlockLayout_19.bin, BackgroundLayout_19, EnemyLayout_19
MapHeader_1C:	maphdr	"level/header/1C.bin", ForegroundLayout_1C, BlockLayout_1C.bin, BackgroundLayout_1C, EnemyLayout_1C
MapHeader_1D:	maphdr	"level/header/1D.bin", ForegroundLayout_1D, BlockLayout_1D.bin, BackgroundLayout_1D, EnemyLayout_1D
MapHeader_4C:	maphdr	"level/header/4C.bin", ForegroundLayout_4C, BlockLayout_4C.bin, BackgroundLayout_4C, EnemyLayout_4C
MapHeader_4D:	maphdr	"level/header/4D.bin", ForegroundLayout_4D, BlockLayout_4D.bin, BackgroundLayout_32_4D_4E_6E_7A, EnemyLayout_4D
MapHeader_49:	maphdr	"level/header/49.bin", ForegroundLayout_49, BlockLayout_49.bin, BackgroundLayout_49_4B, EnemyLayout_49
MapHeader_4B:	maphdr	"level/header/4B.bin", ForegroundLayout_4B, BlockLayout_4B.bin, BackgroundLayout_49_4B, EnemyLayout_4B
MapHeader_4E:	maphdr	"level/header/4E.bin", ForegroundLayout_4E, BlockLayout_4E.bin, BackgroundLayout_32_4D_4E_6E_7A, EnemyLayout_4E
MapHeader_56:	maphdr	"level/header/56.bin", ForegroundLayout_56, BlockLayout_56.bin, BackgroundLayout_56_5C, EnemyLayout_56
MapHeader_2B:	maphdr	"level/header/2B.bin", ForegroundLayout_2B, BlockLayout_2B.bin, BackgroundLayout_2B_31_62, EnemyLayout_2B
MapHeader_0B:	maphdr	"level/header/0B.bin", ForegroundLayout_0B, BlockLayout_0B.bin, BackgroundLayout_0B, EnemyLayout_0B
MapHeader_13:	maphdr	"level/header/13.bin", ForegroundLayout_13, BlockLayout_13.bin, BackgroundLayout_13, EnemyLayout_13
MapHeader_37:	maphdr	"level/header/37.bin", ForegroundLayout_37, BlockLayout_37.bin, BackgroundLayout_37, EnemyLayout_37
MapHeader_30:	maphdr	"level/header/30.bin", ForegroundLayout_30, BlockLayout_30.bin, BackgroundLayout_30, EnemyLayout_30
MapHeader_57:	maphdr	"level/header/57.bin", ForegroundLayout_57, BlockLayout_57.bin, BackgroundLayout_57_5A, EnemyLayout_57
MapHeader_21:	maphdr	"level/header/21.bin", ForegroundLayout_21, BlockLayout_21.bin, BackgroundLayout_21, EnemyLayout_21
MapHeader_25:	maphdr	"level/header/25.bin", ForegroundLayout_25, BlockLayout_25.bin, BackgroundLayout_25, EnemyLayout_25
MapHeader_17:	maphdr	"level/header/17.bin", ForegroundLayout_17, BlockLayout_17.bin, BackgroundLayout_17, EnemyLayout_17
MapHeader_31:	maphdr	"level/header/31.bin", ForegroundLayout_31, BlockLayout_31.bin, BackgroundLayout_2B_31_62, EnemyLayout_31
MapHeader_14:	maphdr	"level/header/14.bin", ForegroundLayout_14, BlockLayout_14.bin, BackgroundLayout_14, EnemyLayout_14
MapHeader_38:	maphdr	"level/header/38.bin", ForegroundLayout_38, BlockLayout_38.bin, BackgroundLayout_38, EnemyLayout_38
MapHeader_35:	maphdr	"level/header/35.bin", ForegroundLayout_35, BlockLayout_35.bin, BackgroundLayout_35, EnemyLayout_35
MapHeader_0C:	maphdr	"level/header/0C.bin", ForegroundLayout_0C, BlockLayout_0C.bin, BackgroundLayout_0C, EnemyLayout_0C
MapHeader_2E:	maphdr	"level/header/2E.bin", ForegroundLayout_2E, BlockLayout_2E.bin, BackgroundLayout_2E, EnemyLayout_2E
MapHeader_34:	maphdr	"level/header/34.bin", ForegroundLayout_34, BlockLayout_34.bin, BackgroundLayout_34, EnemyLayout_34
MapHeader_0A:	maphdr	"level/header/0A.bin", ForegroundLayout_0A, BlockLayout_0A.bin, BackgroundLayout_0A, EnemyLayout_0A
MapHeader_2F:	maphdr	"level/header/2F.bin", ForegroundLayout_2F, BlockLayout_2F.bin, BackgroundLayout_2D_2F, EnemyLayout_2F
MapHeader_39:	maphdr	"level/header/39.bin", ForegroundLayout_39, BlockLayout_39.bin, BackgroundLayout_39, EnemyLayout_39
MapHeader_0F:	maphdr	"level/header/0F.bin", ForegroundLayout_0F, BlockLayout_0F.bin, BackgroundLayout_0F, EnemyLayout_0F
MapHeader_3F:	maphdr	"level/header/3F.bin", ForegroundLayout_3F, BlockLayout_3F.bin, BackgroundLayout_3F, EnemyLayout_3F
MapHeader_3A:	maphdr	"level/header/3A.bin", ForegroundLayout_3A, BlockLayout_3A.bin, BackgroundLayout_3A, EnemyLayout_3A
MapHeader_3B:	maphdr	"level/header/3B.bin", ForegroundLayout_3B, BlockLayout_3B.bin, BackgroundLayout_3B, EnemyLayout_3B
MapHeader_55:	maphdr	"level/header/55.bin", ForegroundLayout_55, BlockLayout_55.bin, BackgroundLayout_53_55, EnemyLayout_55
MapHeader_36:	maphdr	"level/header/36.bin", ForegroundLayout_36, BlockLayout_36.bin, BackgroundLayout_36, EnemyLayout_36
MapHeader_32:	maphdr	"level/header/32.bin", ForegroundLayout_32, BlockLayout_32.bin, BackgroundLayout_32_4D_4E_6E_7A, EnemyLayout_32
MapHeader_53:	maphdr	"level/header/53.bin", ForegroundLayout_53, BlockLayout_53.bin, BackgroundLayout_53_55, EnemyLayout_53
MapHeader_54:	maphdr	"level/header/54.bin", ForegroundLayout_54, BlockLayout_54.bin, BackgroundLayout_54, EnemyLayout_54
MapHeader_0E:	maphdr	"level/header/0E.bin", ForegroundLayout_0E, BlockLayout_0E.bin, BackgroundLayout_0E, EnemyLayout_0E
MapHeader_0D:	maphdr	"level/header/0D.bin", ForegroundLayout_0D, BlockLayout_0D.bin, BackgroundLayout_0D, EnemyLayout_0D
MapHeader_33:	maphdr	"level/header/33.bin", ForegroundLayout_33, BlockLayout_33.bin, BackgroundLayout_33, EnemyLayout_33
MapHeader_5D:	maphdr	"level/header/5D.bin", ForegroundLayout_5D, BlockLayout_5D.bin, BackgroundLayout_5D, EnemyLayout_5D
MapHeader_5E:	maphdr	"level/header/5E.bin", ForegroundLayout_5E, BlockLayout_5E.bin, BackgroundLayout_5E, EnemyLayout_5E
MapHeader_5F:	maphdr	"level/header/5F.bin", ForegroundLayout_5F, BlockLayout_5F.bin, BackgroundLayout_5F, EnemyLayout_5F
MapHeader_60:	maphdr	"level/header/60.bin", ForegroundLayout_60, BlockLayout_60.bin, BackgroundLayout_60, EnemyLayout_60
MapHeader_61:	maphdr	"level/header/61.bin", ForegroundLayout_61, BlockLayout_61.bin, BackgroundLayout_61, EnemyLayout_61
MapHeader_62:	maphdr	"level/header/62.bin", ForegroundLayout_62, BlockLayout_62.bin, BackgroundLayout_2B_31_62, EnemyLayout_62
MapHeader_63:	maphdr	"level/header/63.bin", ForegroundLayout_63, BlockLayout_63.bin, BackgroundLayout_63, EnemyLayout_63
MapHeader_64:	maphdr	"level/header/64.bin", ForegroundLayout_64, BlockLayout_64.bin, BackgroundLayout_64_78, EnemyLayout_64
MapHeader_65:	maphdr	"level/header/65.bin", ForegroundLayout_65, BlockLayout_65.bin, BackgroundLayout_65, EnemyLayout_65
MapHeader_66:	maphdr	"level/header/66.bin", ForegroundLayout_66, BlockLayout_66.bin, BackgroundLayout_66, EnemyLayout_66
MapHeader_67:	maphdr	"level/header/67.bin", ForegroundLayout_67, BlockLayout_67.bin, BackgroundLayout_67, EnemyLayout_67
MapHeader_68:	maphdr	"level/header/68.bin", ForegroundLayout_68, BlockLayout_68.bin, BackgroundLayout_68, EnemyLayout_68
MapHeader_69:	maphdr	"level/header/69.bin", ForegroundLayout_69, BlockLayout_69.bin, BackgroundLayout_69, EnemyLayout_69
MapHeader_6A:	maphdr	"level/header/6A.bin", ForegroundLayout_6A, BlockLayout_6A.bin, BackgroundLayout_6A, EnemyLayout_6A
MapHeader_6B:	maphdr	"level/header/6B.bin", ForegroundLayout_6B, BlockLayout_6B.bin, BackgroundLayout_6B, EnemyLayout_6B
MapHeader_6C:	maphdr	"level/header/6C.bin", ForegroundLayout_6C, BlockLayout_6C.bin, BackgroundLayout_4A_6C_6D_7B, EnemyLayout_6C
MapHeader_6D:	maphdr	"level/header/6D.bin", ForegroundLayout_6D, BlockLayout_6D.bin, BackgroundLayout_4A_6C_6D_7B, EnemyLayout_6D
MapHeader_6E:	maphdr	"level/header/6E.bin", ForegroundLayout_6E, BlockLayout_6E.bin, BackgroundLayout_32_4D_4E_6E_7A, EnemyLayout_6E
MapHeader_6F:	maphdr	"level/header/6F.bin", ForegroundLayout_6F, BlockLayout_6F.bin, BackgroundLayout_6F, EnemyLayout_6F
MapHeader_70:	maphdr	"level/header/70.bin", ForegroundLayout_70, BlockLayout_70.bin, BackgroundLayout_70, EnemyLayout_70
MapHeader_71:	maphdr	"level/header/71.bin", ForegroundLayout_71, BlockLayout_71.bin, BackgroundLayout_71, EnemyLayout_71
MapHeader_72:	maphdr	"level/header/72.bin", ForegroundLayout_72, BlockLayout_72.bin, BackgroundLayout_72, EnemyLayout_72
MapHeader_73:	maphdr	"level/header/73.bin", ForegroundLayout_73, BlockLayout_73.bin, BackgroundLayout_73, EnemyLayout_73
MapHeader_74:	maphdr	"level/header/74.bin", ForegroundLayout_74, BlockLayout_74.bin, BackgroundLayout_74, EnemyLayout_74
MapHeader_75:	maphdr	"level/header/75.bin", ForegroundLayout_75, BlockLayout_75.bin, BackgroundLayout_75, EnemyLayout_75
MapHeader_76:	maphdr	"level/header/76.bin", ForegroundLayout_76, BlockLayout_76.bin, BackgroundLayout_40_76, EnemyLayout_76
MapHeader_77:	maphdr	"level/header/77.bin", ForegroundLayout_77, BlockLayout_77.bin, BackgroundLayout_47_77, EnemyLayout_77
MapHeader_78:	maphdr	"level/header/78.bin", ForegroundLayout_78, BlockLayout_78.bin, BackgroundLayout_64_78, EnemyLayout_78
MapHeader_79:	maphdr	"level/header/79.bin", ForegroundLayout_79, BlockLayout_79.bin, BackgroundLayout_79, EnemyLayout_79
MapHeader_Invalid:
