; Include all relevant platform layouts into the disasm

	if platforms_asm
PlatformLayout_49:   include    "level/platform/49.asm"
PlatformLayout_4C:   include    "level/platform/4C.asm"
PlatformLayout_02:   include    "level/platform/02.asm"
PlatformLayout_40:   include    "level/platform/40.asm"
PlatformLayout_03:   include    "level/platform/03.asm"
PlatformLayout_15:   include    "level/platform/15.asm"
PlatformLayout_16:   include    "level/platform/16.asm"
PlatformLayout_19:   include    "level/platform/19.asm"
PlatformLayout_1A:   include    "level/platform/1A.asm"
PlatformLayout_1C:   include    "level/platform/1C.asm"
PlatformLayout_1D:   include    "level/platform/1D.asm"
PlatformLayout_05:   include    "level/platform/05.asm"
PlatformLayout_04:   include    "level/platform/04.asm"
PlatformLayout_64:   include    "level/platform/64.asm"
PlatformLayout_0A:   include    "level/platform/0A.asm"
PlatformLayout_5C:   include    "level/platform/5C.asm"
PlatformLayout_5A:   include    "level/platform/5A.asm"
PlatformLayout_11:   include    "level/platform/11.asm"
PlatformLayout_57:   include    "level/platform/57.asm"
PlatformLayout_41:   include    "level/platform/41.asm"
PlatformLayout_38:   include    "level/platform/38.asm"
PlatformLayout_10:   include    "level/platform/10.asm"
	else
PlatformLayout_49:   binclude    "level/platform/49.bin"
PlatformLayout_4C:   binclude    "level/platform/4C.bin"
PlatformLayout_02:   binclude    "level/platform/02.bin"
PlatformLayout_40:   binclude    "level/platform/40.bin"
PlatformLayout_03:   binclude    "level/platform/03.bin"
PlatformLayout_15:   binclude    "level/platform/15.bin"
PlatformLayout_16:   binclude    "level/platform/16.bin"
PlatformLayout_19:   binclude    "level/platform/19.bin"
PlatformLayout_1A:   binclude    "level/platform/1A.bin"
PlatformLayout_1C:   binclude    "level/platform/1C.bin"
PlatformLayout_1D:   binclude    "level/platform/1D.bin"
PlatformLayout_05:   binclude    "level/platform/05.bin"
PlatformLayout_04:   binclude    "level/platform/04.bin"
PlatformLayout_64:   binclude    "level/platform/64.bin"
PlatformLayout_0A:   binclude    "level/platform/0A.bin"
PlatformLayout_5C:   binclude    "level/platform/5C.bin"
PlatformLayout_5A:   binclude    "level/platform/5A.bin"
PlatformLayout_11:   binclude    "level/platform/11.bin"
PlatformLayout_57:   binclude    "level/platform/57.bin"
PlatformLayout_41:   binclude    "level/platform/41.bin"
PlatformLayout_38:   binclude    "level/platform/38.bin"
PlatformLayout_10:   binclude    "level/platform/10.bin"
	endif
