	dc.w PlatformLayout_Blank-PlatformLayout_BaseAddress	;00
	dc.w PlatformLayout_Blank-PlatformLayout_BaseAddress	;01
	dc.w PlatformLayout_02-PlatformLayout_BaseAddress	;02
	dc.w PlatformLayout_03-PlatformLayout_BaseAddress	;03
	dc.w PlatformLayout_04-PlatformLayout_BaseAddress	;04
	dc.w PlatformLayout_05-PlatformLayout_BaseAddress	;05
	dc.w PlatformLayout_Blank-PlatformLayout_BaseAddress	;06
	dc.w PlatformLayout_Blank-PlatformLayout_BaseAddress	;07
	dc.w PlatformLayout_Blank-PlatformLayout_BaseAddress	;08
	dc.w PlatformLayout_Blank-PlatformLayout_BaseAddress	;09
	dc.w PlatformLayout_0A-PlatformLayout_BaseAddress	;0A
	dc.w PlatformLayout_Blank-PlatformLayout_BaseAddress	;0B
	dc.w PlatformLayout_Blank-PlatformLayout_BaseAddress	;0C
	dc.w PlatformLayout_Blank-PlatformLayout_BaseAddress	;0D
	dc.w PlatformLayout_Blank-PlatformLayout_BaseAddress	;0E
	dc.w PlatformLayout_Blank-PlatformLayout_BaseAddress	;0F
	dc.w PlatformLayout_10-PlatformLayout_BaseAddress	;10
	dc.w PlatformLayout_11-PlatformLayout_BaseAddress	;11
	dc.w PlatformLayout_Blank-PlatformLayout_BaseAddress	;12
	dc.w PlatformLayout_Blank-PlatformLayout_BaseAddress	;13
	dc.w PlatformLayout_Blank-PlatformLayout_BaseAddress	;14
	dc.w PlatformLayout_15-PlatformLayout_BaseAddress	;15
	dc.w PlatformLayout_16-PlatformLayout_BaseAddress	;16
	dc.w PlatformLayout_Blank-PlatformLayout_BaseAddress	;17
	dc.w PlatformLayout_Blank-PlatformLayout_BaseAddress	;18
	dc.w PlatformLayout_19-PlatformLayout_BaseAddress	;19
	dc.w PlatformLayout_1A-PlatformLayout_BaseAddress	;1A
	dc.w PlatformLayout_Blank-PlatformLayout_BaseAddress	;1B
	dc.w PlatformLayout_1C-PlatformLayout_BaseAddress	;1C
	dc.w PlatformLayout_1D-PlatformLayout_BaseAddress	;1D
	dc.w PlatformLayout_Blank-PlatformLayout_BaseAddress	;1E
	dc.w PlatformLayout_Blank-PlatformLayout_BaseAddress	;1F
	dc.w PlatformLayout_Blank-PlatformLayout_BaseAddress	;20
	dc.w PlatformLayout_Blank-PlatformLayout_BaseAddress	;21
	dc.w PlatformLayout_Blank-PlatformLayout_BaseAddress	;22
	dc.w PlatformLayout_Blank-PlatformLayout_BaseAddress	;23
	dc.w PlatformLayout_Blank-PlatformLayout_BaseAddress	;24
	dc.w PlatformLayout_Blank-PlatformLayout_BaseAddress	;25
	dc.w PlatformLayout_Blank-PlatformLayout_BaseAddress	;26
	dc.w PlatformLayout_Blank-PlatformLayout_BaseAddress	;27
	dc.w PlatformLayout_Blank-PlatformLayout_BaseAddress	;28
	dc.w PlatformLayout_Blank-PlatformLayout_BaseAddress	;29
	dc.w PlatformLayout_Blank-PlatformLayout_BaseAddress	;2A
	dc.w PlatformLayout_Blank-PlatformLayout_BaseAddress	;2B
	dc.w PlatformLayout_Blank-PlatformLayout_BaseAddress	;2C
	dc.w PlatformLayout_Blank-PlatformLayout_BaseAddress	;2D
	dc.w PlatformLayout_Blank-PlatformLayout_BaseAddress	;2E
	dc.w PlatformLayout_Blank-PlatformLayout_BaseAddress	;2F
	dc.w PlatformLayout_Blank-PlatformLayout_BaseAddress	;30
	dc.w PlatformLayout_Blank-PlatformLayout_BaseAddress	;31
	dc.w PlatformLayout_Blank-PlatformLayout_BaseAddress	;32
	dc.w PlatformLayout_Blank-PlatformLayout_BaseAddress	;33
	dc.w PlatformLayout_Blank-PlatformLayout_BaseAddress	;34
	dc.w PlatformLayout_Blank-PlatformLayout_BaseAddress	;35
	dc.w PlatformLayout_Blank-PlatformLayout_BaseAddress	;36
	dc.w PlatformLayout_Blank-PlatformLayout_BaseAddress	;37
	dc.w PlatformLayout_38-PlatformLayout_BaseAddress	;38
	dc.w PlatformLayout_Blank-PlatformLayout_BaseAddress	;39
	dc.w PlatformLayout_Blank-PlatformLayout_BaseAddress	;3A
	dc.w PlatformLayout_Blank-PlatformLayout_BaseAddress	;3B
	dc.w PlatformLayout_Blank-PlatformLayout_BaseAddress	;3C
	dc.w PlatformLayout_Blank-PlatformLayout_BaseAddress	;3D
	dc.w PlatformLayout_Blank-PlatformLayout_BaseAddress	;3E
	dc.w PlatformLayout_Blank-PlatformLayout_BaseAddress	;3F
	dc.w PlatformLayout_40-PlatformLayout_BaseAddress	;40
	dc.w PlatformLayout_41-PlatformLayout_BaseAddress	;41
	dc.w PlatformLayout_Blank-PlatformLayout_BaseAddress	;42
	dc.w PlatformLayout_Blank-PlatformLayout_BaseAddress	;43
	dc.w PlatformLayout_Blank-PlatformLayout_BaseAddress	;44
	dc.w PlatformLayout_Blank-PlatformLayout_BaseAddress	;45
	dc.w PlatformLayout_Blank-PlatformLayout_BaseAddress	;46
	dc.w PlatformLayout_Blank-PlatformLayout_BaseAddress	;47
	dc.w PlatformLayout_Blank-PlatformLayout_BaseAddress	;48
	dc.w PlatformLayout_49-PlatformLayout_BaseAddress	;49
	dc.w PlatformLayout_Blank-PlatformLayout_BaseAddress	;4A
	dc.w PlatformLayout_Blank-PlatformLayout_BaseAddress	;4B
	dc.w PlatformLayout_4C-PlatformLayout_BaseAddress	;4C
	dc.w PlatformLayout_Blank-PlatformLayout_BaseAddress	;4D
	dc.w PlatformLayout_Blank-PlatformLayout_BaseAddress	;4E
	dc.w PlatformLayout_Blank-PlatformLayout_BaseAddress	;4F
	dc.w PlatformLayout_Blank-PlatformLayout_BaseAddress	;50
	dc.w PlatformLayout_Blank-PlatformLayout_BaseAddress	;51
	dc.w PlatformLayout_Blank-PlatformLayout_BaseAddress	;52
	dc.w PlatformLayout_Blank-PlatformLayout_BaseAddress	;53
	dc.w PlatformLayout_Blank-PlatformLayout_BaseAddress	;54
	dc.w PlatformLayout_Blank-PlatformLayout_BaseAddress	;55
	dc.w PlatformLayout_Blank-PlatformLayout_BaseAddress	;56
	dc.w PlatformLayout_57-PlatformLayout_BaseAddress	;57
	dc.w PlatformLayout_Blank-PlatformLayout_BaseAddress	;58
	dc.w PlatformLayout_Blank-PlatformLayout_BaseAddress	;59
	dc.w PlatformLayout_5A-PlatformLayout_BaseAddress	;5A
	dc.w PlatformLayout_Blank-PlatformLayout_BaseAddress	;5B
	dc.w PlatformLayout_5C-PlatformLayout_BaseAddress	;5C
	dc.w PlatformLayout_Blank-PlatformLayout_BaseAddress	;5D
	dc.w PlatformLayout_Blank-PlatformLayout_BaseAddress	;5E
	dc.w PlatformLayout_Blank-PlatformLayout_BaseAddress	;5F
	dc.w PlatformLayout_Blank-PlatformLayout_BaseAddress	;60
	dc.w PlatformLayout_Blank-PlatformLayout_BaseAddress	;61
	dc.w PlatformLayout_Blank-PlatformLayout_BaseAddress	;62
	dc.w PlatformLayout_Blank-PlatformLayout_BaseAddress	;63
	dc.w PlatformLayout_64-PlatformLayout_BaseAddress	;64
	dc.w PlatformLayout_Blank-PlatformLayout_BaseAddress	;65
	dc.w PlatformLayout_Blank-PlatformLayout_BaseAddress	;66
	dc.w PlatformLayout_Blank-PlatformLayout_BaseAddress	;67
	dc.w PlatformLayout_Blank-PlatformLayout_BaseAddress	;68
	dc.w PlatformLayout_Blank-PlatformLayout_BaseAddress	;69
	dc.w PlatformLayout_Blank-PlatformLayout_BaseAddress	;6A
	dc.w PlatformLayout_Blank-PlatformLayout_BaseAddress	;6B
	dc.w PlatformLayout_Blank-PlatformLayout_BaseAddress	;6C
	dc.w PlatformLayout_Blank-PlatformLayout_BaseAddress	;6D
	dc.w PlatformLayout_Blank-PlatformLayout_BaseAddress	;6E
	dc.w PlatformLayout_Blank-PlatformLayout_BaseAddress	;6F
	dc.w PlatformLayout_Blank-PlatformLayout_BaseAddress	;70
	dc.w PlatformLayout_Blank-PlatformLayout_BaseAddress	;71
	dc.w PlatformLayout_Blank-PlatformLayout_BaseAddress	;72
	dc.w PlatformLayout_Blank-PlatformLayout_BaseAddress	;73
	dc.w PlatformLayout_Blank-PlatformLayout_BaseAddress	;74
	dc.w PlatformLayout_Blank-PlatformLayout_BaseAddress	;75
	dc.w PlatformLayout_Blank-PlatformLayout_BaseAddress	;76
	dc.w PlatformLayout_Blank-PlatformLayout_BaseAddress	;77
	dc.w PlatformLayout_Blank-PlatformLayout_BaseAddress	;78
	dc.w PlatformLayout_Blank-PlatformLayout_BaseAddress	;79
	dc.w PlatformLayout_Blank-PlatformLayout_BaseAddress	;7A
	dc.w PlatformLayout_Blank-PlatformLayout_BaseAddress	;7B
	dc.w PlatformLayout_Blank-PlatformLayout_BaseAddress	;7C
	dc.w PlatformLayout_Blank-PlatformLayout_BaseAddress	;7D
